#!/bin/sh
#FLUSH REGLES
iptables -F
iptables -X
iptables -Z
iptables -t nat -F

#Politica per defecte
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -t nat -P PREROUTING ACCEPT
iptables -t nat -P POSTROUTING ACCEPT

echo 1 > /proc/sys/net/ipv4/ip-forward

iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to 10.1.6.10:80
iptables -A FORWARD -s 10.10.1.0/24 -d 10.1.6.0/24 -p tcp --dport 1:1024 -j ACCEPT
iptables -A FORWARD -d 10.10.1.0/24 -s 10.1.6.0/24 -p tcp --sport 1:1024 -j ACCEPT

